apiVersion: v1
kind: Service
metadata:
  name: vertx-greet
  namespace: canary-release
  labels:
    app: vertx-greet
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: vertx-greet
