---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-delay
  labels:
    istio-injection: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: chaos-delay
  labels:
    app: customer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
      version: v1
  template:
    metadata:
      labels:
        app: customer
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: customer
        image: quay.io/redhattraining/ossm-customer:1.0
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTIONS
          value: -Xms15m -Xmx15m -Xmn15m
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/live
          initialDelaySeconds: 5
          periodSeconds: 4
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/ready
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: chaos-delay
  labels:
    app: customer
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: customer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preference
  namespace: chaos-delay
  labels:
    app: preference
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preference
      version: v1
  template:
    metadata:
      labels:
        app: preference
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: preference
        image: quay.io/redhattraining/ossm-preference:1.0
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTIONS
          value: -Xms15m -Xmx15m -Xmn15m
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/live
          initialDelaySeconds: 5
          periodSeconds: 4
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/ready
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: preference
  namespace: chaos-delay
  labels:
    app: preference
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: preference
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: chaos-delay
  labels:
    app: recommendation
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
      version: v1
  template:
    metadata:
      labels:
        app: recommendation
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: recommendation
        image: quay.io/redhattraining/ossm-recommendation:1.0
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTIONS
          value: -Xms15m -Xmx15m -Xmn15m
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/live
          initialDelaySeconds: 5
          periodSeconds: 4
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health/ready
          initialDelaySeconds: 6
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: chaos-delay
  labels:
    app: recommendation
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: delay-gateway
  namespace: chaos-delay
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "delay.example.com"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: customer-virtualservice
  namespace: chaos-delay
spec:
  hosts:
  - "delay.example.com"
  gateways:
  - delay-gateway
  http:
  - match:
    - uri:
        prefix: /delay
    retries:
      attempts: 0
    rewrite:
      uri: /
    route:
    - destination:
        host: customer
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: preference-virtualservice
  namespace: chaos-delay
spec:
  hosts:
  - preference
  http:
  - retries:
      attempts: 0
    route:
    - destination:
        host: preference
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendation
  namespace: chaos-delay
spec:
  hosts:
  - recommendation
  http:
  - fault:
      delay:
        fixedDelay: 4s ##  curl -m 2 delay.example.com
        percentage:
          value: 50.0
    route:
    - destination:
        host: recommendation
